
export type Language = 'en' | 'tr' | 'hi';

export type View = 
  | 'dashboard' 
  | 'procurement-orders' 
  | 'procurement-prices' 
  | 'procurement-escalation' 
  | 'procurement-suppliers' 
  | 'procurement-bom' 
  | 'logistics-reservation'
  | 'logistics-transport'
  | 'warehouse-dashboard' 
  | 'warehouse-inefficiency'
  | 'customs-dashboard'
  | 'customs-import'
  | 'customs-export';

export interface Translations {
  title: string;
  dashboard: string;
  procurement: string;
  logistics: string;
  warehouse: string;
  customs: string;
  aiInsights: string;
  totalBudget: string;
  actualSpend: string;
  unitPrice: string;
  quantity: string;
  efficiency: string;
  activeShipments: string;
  stockLevel: string;
  clearedItems: string;
  analyze: string;
  generating: string;
  salesTarget: string;
  variance: string;
  orderAnalysis: string;
  priceAnalysis: string;
  supplierPerformance: string;
  bomControl: string;
  budgetQty: string;
  actualQty: string;
  budgetPrice: string;
  actualPrice: string;
  budgetTotal: string;
  actualTotal: string;
  bomStatus: string;
  purchaseReq: string;
  purchaseOrder: string;
  customerOrder: string;
  status: string;
  mrpResult: string;
  component: string;
  errorCode: string;
  errorDetail: string;
  impactedReq: string;
  impactedPO: string;
  correctiveAction: string;
  escalationAnalysis: string;
  rawMaterial: string;
  labor: string;
  energy: string;
  other: string;
  currentPrice: string;
  newPrice: string;
  difference: string;
  budgetImpact: string;
  actualImpact: string;
  costBreakdown: string;
  targetPrice: string;
  overTargetPrice: string;
  overTargetImpact: string;
  overTargetQty: string;
  overBudgetPurchaseQty: string;
  overBudgetAvgPrice: string;
  overBudgetImpact: string;
  exchangeRateEffect: string;
  inflationEffect: string;
  macroDrivers: string;
  fxRate: string;
  inflationRate: string;
  reservationPerformance: string;
  salesRep: string;
  customer: string;
  product: string;
  waitTimeDays: string;
  stockCostImpact: string;
  financialImpact: string;
  opportunityLoss: string;
  totalImpact: string;
  thresholdWarning: string;
  stockCount: string;
  overtime: string;
  inefficiencyCosts: string;
  unnecessaryMovements: string;
  pickingCancellations: string;
  productWaitTime: string;
  movementList: string;
  inventoryTurnover: string;
  emptyShelfRate: string;
  costEffect: string;
  warehousePerformance: string;
  transportation: string;
  importShipments: string;
  exportShipments: string;
  localShipments: string;
  vehicleUtilization: string;
  shipmentPlan: string;
  loadFactor: string;
  destination: string;
  origin: string;
  eta: string;
  vesselVehicle: string;
  customsManagement: string;
  importDetails: string;
  exportDetails: string;
  declarationNo: string;
  hsCode: string;
  dutiesPaid: string;
  vesselName: string;
  clearanceTime: string;
  customsMap: string;
  performAnalysis: string;
  fetchingData: string;
  orderSummaryYear: string;
  openOrders: string;
  delayed: string;
  budgetQtyDiff: string;
  budgetPriceDiff: string;
  warehouseDeliveryDate: string;
  palletCount: string;
  totalBudgetImpact: string;
  originCountry: string;
  // Dashboard & Specific labels
  vsLastMonth: string;
  delayRisk: string;
  nearingCapacity: string;
  optimalPerformance: string;
  budgetPriceSync: string;
  fleetDistribution: string;
  inventoryLabor: string;
  complianceDuties: string;
  budgetUtilization: string;
  unitPriceVariance: string;
  vehicleLoadEfficiency: string;
  onTimeArrivalRate: string;
  globalOtdRating: string;
  stockMovements: string;
  clearanceThroughput: string;
  dutySavingsTracker: string;
  totalRecovery: string;
  targetReached: string;
  fastLane: string;
  performanceAudit: string;
  used: string;
  remaining: string;
  full: string;
  partial: string;
  under: string;
  days: string;
  hours: string;
  utilized: string;
  target: string;
  systemStatus: string;
  systemOptimized: string;
  clickAnalyze: string;
  errorInsight: string;
  componentsCat: string;
  packagingCat: string;
  mroCat: string;
  actualLegend: string;
  budgetLegend: string;
  orderPlural: string;
  budgetLabel: string;
  itemCode: string;
  itemName: string;
  deliveryDate: string;
  actualShort: string;
  budgetShort: string;
  // Hard-to-find strings
  overtimeBreakdownWeekly: string;
  stockLevelByCategory: string;
  importLabel: string;
  exportLabel: string;
  localLabel: string;
  stockItem: string;
  current: string;
  new: string;
  vol: string;
  vendorName: string;
  supplyChainHealth: string;
  errorCategory: string;
  details: string;
  loads: string;
}
